server:
  port: 8091

eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

spring:
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/